// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pdpb.proto

package pdpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreState int32

const (
	StoreState_UP        StoreState = 0
	StoreState_OFFLINE   StoreState = 1 // 手动下线
	StoreState_TOMBSTONE StoreState = 2 // 已删除
)

// Enum value maps for StoreState.
var (
	StoreState_name = map[int32]string{
		0: "UP",
		1: "OFFLINE",
		2: "TOMBSTONE",
	}
	StoreState_value = map[string]int32{
		"UP":        0,
		"OFFLINE":   1,
		"TOMBSTONE": 2,
	}
)

func (x StoreState) Enum() *StoreState {
	p := new(StoreState)
	*p = x
	return p
}

func (x StoreState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StoreState) Descriptor() protoreflect.EnumDescriptor {
	return file_pdpb_proto_enumTypes[0].Descriptor()
}

func (StoreState) Type() protoreflect.EnumType {
	return &file_pdpb_proto_enumTypes[0]
}

func (x StoreState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StoreState.Descriptor instead.
func (StoreState) EnumDescriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{0}
}

type ChangePeer_ChangeType int32

const (
	ChangePeer_ADD_NODE    ChangePeer_ChangeType = 0
	ChangePeer_REMOVE_NODE ChangePeer_ChangeType = 1 // ADD_LEARNER = 2;
)

// Enum value maps for ChangePeer_ChangeType.
var (
	ChangePeer_ChangeType_name = map[int32]string{
		0: "ADD_NODE",
		1: "REMOVE_NODE",
	}
	ChangePeer_ChangeType_value = map[string]int32{
		"ADD_NODE":    0,
		"REMOVE_NODE": 1,
	}
)

func (x ChangePeer_ChangeType) Enum() *ChangePeer_ChangeType {
	p := new(ChangePeer_ChangeType)
	*p = x
	return p
}

func (x ChangePeer_ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangePeer_ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_pdpb_proto_enumTypes[1].Descriptor()
}

func (ChangePeer_ChangeType) Type() protoreflect.EnumType {
	return &file_pdpb_proto_enumTypes[1]
}

func (x ChangePeer_ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangePeer_ChangeType.Descriptor instead.
func (ChangePeer_ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{20, 0}
}

type AllocIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocIDRequest) Reset() {
	*x = AllocIDRequest{}
	mi := &file_pdpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocIDRequest) ProtoMessage() {}

func (x *AllocIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocIDRequest.ProtoReflect.Descriptor instead.
func (*AllocIDRequest) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{0}
}

type AllocIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocIDResponse) Reset() {
	*x = AllocIDResponse{}
	mi := &file_pdpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocIDResponse) ProtoMessage() {}

func (x *AllocIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocIDResponse.ProtoReflect.Descriptor instead.
func (*AllocIDResponse) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{1}
}

func (x *AllocIDResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MetaStore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	State         StoreState             `protobuf:"varint,3,opt,name=state,proto3,enum=pdpb.StoreState" json:"state,omitempty"`
	Labels        []*StoreLabel          `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`   // 机房、机架信息，用于调度
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"` // TitanKV 版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaStore) Reset() {
	*x = MetaStore{}
	mi := &file_pdpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaStore) ProtoMessage() {}

func (x *MetaStore) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaStore.ProtoReflect.Descriptor instead.
func (*MetaStore) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{2}
}

func (x *MetaStore) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MetaStore) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MetaStore) GetState() StoreState {
	if x != nil {
		return x.State
	}
	return StoreState_UP
}

func (x *MetaStore) GetLabels() []*StoreLabel {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetaStore) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type StoreLabel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreLabel) Reset() {
	*x = StoreLabel{}
	mi := &file_pdpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreLabel) ProtoMessage() {}

func (x *StoreLabel) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreLabel.ProtoReflect.Descriptor instead.
func (*StoreLabel) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{3}
}

func (x *StoreLabel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreLabel) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type StoreStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Capacity           uint64                 `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Available          uint64                 `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	RegionCount        uint32                 `protobuf:"varint,3,opt,name=region_count,json=regionCount,proto3" json:"region_count,omitempty"`
	SendingSnapCount   uint32                 `protobuf:"varint,4,opt,name=sending_snap_count,json=sendingSnapCount,proto3" json:"sending_snap_count,omitempty"`
	ReceivingSnapCount uint32                 `protobuf:"varint,5,opt,name=receiving_snap_count,json=receivingSnapCount,proto3" json:"receiving_snap_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StoreStats) Reset() {
	*x = StoreStats{}
	mi := &file_pdpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreStats) ProtoMessage() {}

func (x *StoreStats) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreStats.ProtoReflect.Descriptor instead.
func (*StoreStats) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{4}
}

func (x *StoreStats) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *StoreStats) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *StoreStats) GetRegionCount() uint32 {
	if x != nil {
		return x.RegionCount
	}
	return 0
}

func (x *StoreStats) GetSendingSnapCount() uint32 {
	if x != nil {
		return x.SendingSnapCount
	}
	return 0
}

func (x *StoreStats) GetReceivingSnapCount() uint32 {
	if x != nil {
		return x.ReceivingSnapCount
	}
	return 0
}

type PutStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         *MetaStore             `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutStoreRequest) Reset() {
	*x = PutStoreRequest{}
	mi := &file_pdpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutStoreRequest) ProtoMessage() {}

func (x *PutStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutStoreRequest.ProtoReflect.Descriptor instead.
func (*PutStoreRequest) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{5}
}

func (x *PutStoreRequest) GetStore() *MetaStore {
	if x != nil {
		return x.Store
	}
	return nil
}

type PutStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutStoreResponse) Reset() {
	*x = PutStoreResponse{}
	mi := &file_pdpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutStoreResponse) ProtoMessage() {}

func (x *PutStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutStoreResponse.ProtoReflect.Descriptor instead.
func (*PutStoreResponse) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{6}
}

type StoreHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       uint64                 `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Stats         *StoreStats            `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreHeartbeatRequest) Reset() {
	*x = StoreHeartbeatRequest{}
	mi := &file_pdpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreHeartbeatRequest) ProtoMessage() {}

func (x *StoreHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*StoreHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{7}
}

func (x *StoreHeartbeatRequest) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *StoreHeartbeatRequest) GetStats() *StoreStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type StoreHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreHeartbeatResponse) Reset() {
	*x = StoreHeartbeatResponse{}
	mi := &file_pdpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreHeartbeatResponse) ProtoMessage() {}

func (x *StoreHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*StoreHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{8}
}

type GetTSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // 一次申请多少个 TS (通常是 1 个，用于批处理优化)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTSRequest) Reset() {
	*x = GetTSRequest{}
	mi := &file_pdpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTSRequest) ProtoMessage() {}

func (x *GetTSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTSRequest.ProtoReflect.Descriptor instead.
func (*GetTSRequest) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{9}
}

func (x *GetTSRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Physical      int64                  `protobuf:"varint,1,opt,name=physical,proto3" json:"physical,omitempty"` // 物理时钟 (毫秒)
	Logical       int64                  `protobuf:"varint,2,opt,name=logical,proto3" json:"logical,omitempty"`   // 逻辑时钟
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_pdpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{10}
}

func (x *Timestamp) GetPhysical() int64 {
	if x != nil {
		return x.Physical
	}
	return 0
}

func (x *Timestamp) GetLogical() int64 {
	if x != nil {
		return x.Logical
	}
	return 0
}

type GetTSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *Timestamp             `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 返回的起始时间戳
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`        // 返回的数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTSResponse) Reset() {
	*x = GetTSResponse{}
	mi := &file_pdpb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTSResponse) ProtoMessage() {}

func (x *GetTSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTSResponse.ProtoReflect.Descriptor instead.
func (*GetTSResponse) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{11}
}

func (x *GetTSResponse) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetTSResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Region struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Range: [start_key, end_key)
	StartKey      []byte       `protobuf:"bytes,2,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        []byte       `protobuf:"bytes,3,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	RegionEpoch   *RegionEpoch `protobuf:"bytes,4,opt,name=region_epoch,json=regionEpoch,proto3" json:"region_epoch,omitempty"` // 版本控制，防止脑裂和过时路由
	Peers         []*Peer      `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_pdpb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{12}
}

func (x *Region) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Region) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *Region) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *Region) GetRegionEpoch() *RegionEpoch {
	if x != nil {
		return x.RegionEpoch
	}
	return nil
}

func (x *Region) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StoreId       uint64                 `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"` // bool is_learner = 3; // 进阶：Learner 角色
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_pdpb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{13}
}

func (x *Peer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Peer) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

// Region 版本，用于 Split/Merge 保护
type RegionEpoch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 配置变更版本 (AddPeer/RemovePeer)
	ConfVer uint64 `protobuf:"varint,1,opt,name=conf_ver,json=confVer,proto3" json:"conf_ver,omitempty"`
	// 分裂/合并版本 (Split/Merge)
	Version       uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionEpoch) Reset() {
	*x = RegionEpoch{}
	mi := &file_pdpb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionEpoch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionEpoch) ProtoMessage() {}

func (x *RegionEpoch) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionEpoch.ProtoReflect.Descriptor instead.
func (*RegionEpoch) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{14}
}

func (x *RegionEpoch) GetConfVer() uint64 {
	if x != nil {
		return x.ConfVer
	}
	return 0
}

func (x *RegionEpoch) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionRequest) Reset() {
	*x = GetRegionRequest{}
	mi := &file_pdpb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionRequest) ProtoMessage() {}

func (x *GetRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionRequest.ProtoReflect.Descriptor instead.
func (*GetRegionRequest) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{15}
}

func (x *GetRegionRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetRegionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        *Region                `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Leader        *Peer                  `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"` // 告诉 Client 谁是 Leader
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionResponse) Reset() {
	*x = GetRegionResponse{}
	mi := &file_pdpb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionResponse) ProtoMessage() {}

func (x *GetRegionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionResponse.ProtoReflect.Descriptor instead.
func (*GetRegionResponse) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{16}
}

func (x *GetRegionResponse) GetRegion() *Region {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *GetRegionResponse) GetLeader() *Peer {
	if x != nil {
		return x.Leader
	}
	return nil
}

type RegionHeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Region 的元数据 (Range, Epoch, Peers)
	Region *Region `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// 当前的 Leader 是谁
	Leader *Peer `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	// --- 以下字段用于 Week 9 调度 (Day 4 先占位) ---
	// Region 的大概大小 (MB)
	ApproximateSize uint64 `protobuf:"varint,3,opt,name=approximate_size,json=approximateSize,proto3" json:"approximate_size,omitempty"`
	// Region 包含的 Key 数量
	ApproximateKeys uint64 `protobuf:"varint,4,opt,name=approximate_keys,json=approximateKeys,proto3" json:"approximate_keys,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegionHeartbeatRequest) Reset() {
	*x = RegionHeartbeatRequest{}
	mi := &file_pdpb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionHeartbeatRequest) ProtoMessage() {}

func (x *RegionHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*RegionHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{17}
}

func (x *RegionHeartbeatRequest) GetRegion() *Region {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *RegionHeartbeatRequest) GetLeader() *Peer {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *RegionHeartbeatRequest) GetApproximateSize() uint64 {
	if x != nil {
		return x.ApproximateSize
	}
	return 0
}

func (x *RegionHeartbeatRequest) GetApproximateKeys() uint64 {
	if x != nil {
		return x.ApproximateKeys
	}
	return 0
}

type TransferLeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        uint64                 `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`    // 目标 Peer ID
	StoreId       uint64                 `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"` // 目标 Store ID (辅助校验)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferLeader) Reset() {
	*x = TransferLeader{}
	mi := &file_pdpb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferLeader) ProtoMessage() {}

func (x *TransferLeader) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferLeader.ProtoReflect.Descriptor instead.
func (*TransferLeader) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{18}
}

func (x *TransferLeader) GetPeerId() uint64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *TransferLeader) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

type RegionHeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 可选：返回一个 TSO 用于校准
	TransferLeader *TransferLeader        `protobuf:"bytes,2,opt,name=transfer_leader,json=transferLeader,proto3" json:"transfer_leader,omitempty"`
	ChangePeer     *ChangePeer            `protobuf:"bytes,3,opt,name=change_peer,json=changePeer,proto3" json:"change_peer,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegionHeartbeatResponse) Reset() {
	*x = RegionHeartbeatResponse{}
	mi := &file_pdpb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionHeartbeatResponse) ProtoMessage() {}

func (x *RegionHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*RegionHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{19}
}

func (x *RegionHeartbeatResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RegionHeartbeatResponse) GetTransferLeader() *TransferLeader {
	if x != nil {
		return x.TransferLeader
	}
	return nil
}

func (x *RegionHeartbeatResponse) GetChangePeer() *ChangePeer {
	if x != nil {
		return x.ChangePeer
	}
	return nil
}

type ChangePeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeType    ChangePeer_ChangeType  `protobuf:"varint,1,opt,name=change_type,json=changeType,proto3,enum=pdpb.ChangePeer_ChangeType" json:"change_type,omitempty"`
	Peer          *Peer                  `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"` // 包含 PeerID 和 StoreID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePeer) Reset() {
	*x = ChangePeer{}
	mi := &file_pdpb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePeer) ProtoMessage() {}

func (x *ChangePeer) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePeer.ProtoReflect.Descriptor instead.
func (*ChangePeer) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{20}
}

func (x *ChangePeer) GetChangeType() ChangePeer_ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ChangePeer_ADD_NODE
}

func (x *ChangePeer) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type RegionContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	RegionEpoch   *RegionEpoch           `protobuf:"bytes,2,opt,name=region_epoch,json=regionEpoch,proto3" json:"region_epoch,omitempty"` // 客户端持有的版本号
	Peer          *Peer                  `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`                                  // 客户端认为自己正在发给谁
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionContext) Reset() {
	*x = RegionContext{}
	mi := &file_pdpb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionContext) ProtoMessage() {}

func (x *RegionContext) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionContext.ProtoReflect.Descriptor instead.
func (*RegionContext) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{21}
}

func (x *RegionContext) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *RegionContext) GetRegionEpoch() *RegionEpoch {
	if x != nil {
		return x.RegionEpoch
	}
	return nil
}

func (x *RegionContext) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RegionContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // 【新增】
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_pdpb_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{22}
}

func (x *PutRequest) GetContext() *RegionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RegionContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // 【新增】
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_pdpb_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{23}
}

func (x *GetRequest) GetContext() *RegionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RegionContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // 【新增】
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_pdpb_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteRequest) GetContext() *RegionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       uint64                 `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreRequest) Reset() {
	*x = GetStoreRequest{}
	mi := &file_pdpb_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreRequest) ProtoMessage() {}

func (x *GetStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreRequest.ProtoReflect.Descriptor instead.
func (*GetStoreRequest) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{25}
}

func (x *GetStoreRequest) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

type GetStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         *MetaStore             `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreResponse) Reset() {
	*x = GetStoreResponse{}
	mi := &file_pdpb_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreResponse) ProtoMessage() {}

func (x *GetStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreResponse.ProtoReflect.Descriptor instead.
func (*GetStoreResponse) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{26}
}

func (x *GetStoreResponse) GetStore() *MetaStore {
	if x != nil {
		return x.Store
	}
	return nil
}

var File_pdpb_proto protoreflect.FileDescriptor

const file_pdpb_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"pdpb.proto\x12\x04pdpb\"\x10\n" +
	"\x0eAllocIDRequest\"!\n" +
	"\x0fAllocIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xa1\x01\n" +
	"\tMetaStore\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12&\n" +
	"\x05state\x18\x03 \x01(\x0e2\x10.pdpb.StoreStateR\x05state\x12(\n" +
	"\x06labels\x18\x04 \x03(\v2\x10.pdpb.StoreLabelR\x06labels\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"4\n" +
	"\n" +
	"StoreLabel\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc9\x01\n" +
	"\n" +
	"StoreStats\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x04R\bcapacity\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x04R\tavailable\x12!\n" +
	"\fregion_count\x18\x03 \x01(\rR\vregionCount\x12,\n" +
	"\x12sending_snap_count\x18\x04 \x01(\rR\x10sendingSnapCount\x120\n" +
	"\x14receiving_snap_count\x18\x05 \x01(\rR\x12receivingSnapCount\"8\n" +
	"\x0fPutStoreRequest\x12%\n" +
	"\x05store\x18\x01 \x01(\v2\x0f.pdpb.MetaStoreR\x05store\"\x12\n" +
	"\x10PutStoreResponse\"Z\n" +
	"\x15StoreHeartbeatRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x04R\astoreId\x12&\n" +
	"\x05stats\x18\x02 \x01(\v2\x10.pdpb.StoreStatsR\x05stats\"\x18\n" +
	"\x16StoreHeartbeatResponse\"$\n" +
	"\fGetTSRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\"A\n" +
	"\tTimestamp\x12\x1a\n" +
	"\bphysical\x18\x01 \x01(\x03R\bphysical\x12\x18\n" +
	"\alogical\x18\x02 \x01(\x03R\alogical\"T\n" +
	"\rGetTSResponse\x12-\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x0f.pdpb.TimestampR\ttimestamp\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"\xa6\x01\n" +
	"\x06Region\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tstart_key\x18\x02 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x03 \x01(\fR\x06endKey\x124\n" +
	"\fregion_epoch\x18\x04 \x01(\v2\x11.pdpb.RegionEpochR\vregionEpoch\x12 \n" +
	"\x05peers\x18\x05 \x03(\v2\n" +
	".pdpb.PeerR\x05peers\"1\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\x04R\astoreId\"B\n" +
	"\vRegionEpoch\x12\x19\n" +
	"\bconf_ver\x18\x01 \x01(\x04R\aconfVer\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"$\n" +
	"\x10GetRegionRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"]\n" +
	"\x11GetRegionResponse\x12$\n" +
	"\x06region\x18\x01 \x01(\v2\f.pdpb.RegionR\x06region\x12\"\n" +
	"\x06leader\x18\x02 \x01(\v2\n" +
	".pdpb.PeerR\x06leader\"\xb8\x01\n" +
	"\x16RegionHeartbeatRequest\x12$\n" +
	"\x06region\x18\x01 \x01(\v2\f.pdpb.RegionR\x06region\x12\"\n" +
	"\x06leader\x18\x02 \x01(\v2\n" +
	".pdpb.PeerR\x06leader\x12)\n" +
	"\x10approximate_size\x18\x03 \x01(\x04R\x0fapproximateSize\x12)\n" +
	"\x10approximate_keys\x18\x04 \x01(\x04R\x0fapproximateKeys\"D\n" +
	"\x0eTransferLeader\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x04R\x06peerId\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\x04R\astoreId\"\xa9\x01\n" +
	"\x17RegionHeartbeatResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12=\n" +
	"\x0ftransfer_leader\x18\x02 \x01(\v2\x14.pdpb.TransferLeaderR\x0etransferLeader\x121\n" +
	"\vchange_peer\x18\x03 \x01(\v2\x10.pdpb.ChangePeerR\n" +
	"changePeer\"\x97\x01\n" +
	"\n" +
	"ChangePeer\x12<\n" +
	"\vchange_type\x18\x01 \x01(\x0e2\x1b.pdpb.ChangePeer.ChangeTypeR\n" +
	"changeType\x12\x1e\n" +
	"\x04peer\x18\x02 \x01(\v2\n" +
	".pdpb.PeerR\x04peer\"+\n" +
	"\n" +
	"ChangeType\x12\f\n" +
	"\bADD_NODE\x10\x00\x12\x0f\n" +
	"\vREMOVE_NODE\x10\x01\"\x82\x01\n" +
	"\rRegionContext\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x124\n" +
	"\fregion_epoch\x18\x02 \x01(\v2\x11.pdpb.RegionEpochR\vregionEpoch\x12\x1e\n" +
	"\x04peer\x18\x03 \x01(\v2\n" +
	".pdpb.PeerR\x04peer\"c\n" +
	"\n" +
	"PutRequest\x12-\n" +
	"\acontext\x18\x01 \x01(\v2\x13.pdpb.RegionContextR\acontext\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"M\n" +
	"\n" +
	"GetRequest\x12-\n" +
	"\acontext\x18\x01 \x01(\v2\x13.pdpb.RegionContextR\acontext\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"P\n" +
	"\rDeleteRequest\x12-\n" +
	"\acontext\x18\x01 \x01(\v2\x13.pdpb.RegionContextR\acontext\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\",\n" +
	"\x0fGetStoreRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x04R\astoreId\"9\n" +
	"\x10GetStoreResponse\x12%\n" +
	"\x05store\x18\x01 \x01(\v2\x0f.pdpb.MetaStoreR\x05store*0\n" +
	"\n" +
	"StoreState\x12\x06\n" +
	"\x02UP\x10\x00\x12\v\n" +
	"\aOFFLINE\x10\x01\x12\r\n" +
	"\tTOMBSTONE\x10\x022\xbf\x03\n" +
	"\x02PD\x120\n" +
	"\x05GetTS\x12\x12.pdpb.GetTSRequest\x1a\x13.pdpb.GetTSResponse\x129\n" +
	"\bPutStore\x12\x15.pdpb.PutStoreRequest\x1a\x16.pdpb.PutStoreResponse\x12K\n" +
	"\x0eStoreHeartbeat\x12\x1b.pdpb.StoreHeartbeatRequest\x1a\x1c.pdpb.StoreHeartbeatResponse\x126\n" +
	"\aAllocID\x12\x14.pdpb.AllocIDRequest\x1a\x15.pdpb.AllocIDResponse\x12<\n" +
	"\tGetRegion\x12\x16.pdpb.GetRegionRequest\x1a\x17.pdpb.GetRegionResponse\x12N\n" +
	"\x0fRegionHeartbeat\x12\x1c.pdpb.RegionHeartbeatRequest\x1a\x1d.pdpb.RegionHeartbeatResponse\x129\n" +
	"\bGetStore\x12\x15.pdpb.GetStoreRequest\x1a\x16.pdpb.GetStoreResponseB\x15Z\x13titankv/pd/api/pdpbb\x06proto3"

var (
	file_pdpb_proto_rawDescOnce sync.Once
	file_pdpb_proto_rawDescData []byte
)

func file_pdpb_proto_rawDescGZIP() []byte {
	file_pdpb_proto_rawDescOnce.Do(func() {
		file_pdpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pdpb_proto_rawDesc), len(file_pdpb_proto_rawDesc)))
	})
	return file_pdpb_proto_rawDescData
}

var file_pdpb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pdpb_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_pdpb_proto_goTypes = []any{
	(StoreState)(0),                 // 0: pdpb.StoreState
	(ChangePeer_ChangeType)(0),      // 1: pdpb.ChangePeer.ChangeType
	(*AllocIDRequest)(nil),          // 2: pdpb.AllocIDRequest
	(*AllocIDResponse)(nil),         // 3: pdpb.AllocIDResponse
	(*MetaStore)(nil),               // 4: pdpb.MetaStore
	(*StoreLabel)(nil),              // 5: pdpb.StoreLabel
	(*StoreStats)(nil),              // 6: pdpb.StoreStats
	(*PutStoreRequest)(nil),         // 7: pdpb.PutStoreRequest
	(*PutStoreResponse)(nil),        // 8: pdpb.PutStoreResponse
	(*StoreHeartbeatRequest)(nil),   // 9: pdpb.StoreHeartbeatRequest
	(*StoreHeartbeatResponse)(nil),  // 10: pdpb.StoreHeartbeatResponse
	(*GetTSRequest)(nil),            // 11: pdpb.GetTSRequest
	(*Timestamp)(nil),               // 12: pdpb.Timestamp
	(*GetTSResponse)(nil),           // 13: pdpb.GetTSResponse
	(*Region)(nil),                  // 14: pdpb.Region
	(*Peer)(nil),                    // 15: pdpb.Peer
	(*RegionEpoch)(nil),             // 16: pdpb.RegionEpoch
	(*GetRegionRequest)(nil),        // 17: pdpb.GetRegionRequest
	(*GetRegionResponse)(nil),       // 18: pdpb.GetRegionResponse
	(*RegionHeartbeatRequest)(nil),  // 19: pdpb.RegionHeartbeatRequest
	(*TransferLeader)(nil),          // 20: pdpb.TransferLeader
	(*RegionHeartbeatResponse)(nil), // 21: pdpb.RegionHeartbeatResponse
	(*ChangePeer)(nil),              // 22: pdpb.ChangePeer
	(*RegionContext)(nil),           // 23: pdpb.RegionContext
	(*PutRequest)(nil),              // 24: pdpb.PutRequest
	(*GetRequest)(nil),              // 25: pdpb.GetRequest
	(*DeleteRequest)(nil),           // 26: pdpb.DeleteRequest
	(*GetStoreRequest)(nil),         // 27: pdpb.GetStoreRequest
	(*GetStoreResponse)(nil),        // 28: pdpb.GetStoreResponse
}
var file_pdpb_proto_depIdxs = []int32{
	0,  // 0: pdpb.MetaStore.state:type_name -> pdpb.StoreState
	5,  // 1: pdpb.MetaStore.labels:type_name -> pdpb.StoreLabel
	4,  // 2: pdpb.PutStoreRequest.store:type_name -> pdpb.MetaStore
	6,  // 3: pdpb.StoreHeartbeatRequest.stats:type_name -> pdpb.StoreStats
	12, // 4: pdpb.GetTSResponse.timestamp:type_name -> pdpb.Timestamp
	16, // 5: pdpb.Region.region_epoch:type_name -> pdpb.RegionEpoch
	15, // 6: pdpb.Region.peers:type_name -> pdpb.Peer
	14, // 7: pdpb.GetRegionResponse.region:type_name -> pdpb.Region
	15, // 8: pdpb.GetRegionResponse.leader:type_name -> pdpb.Peer
	14, // 9: pdpb.RegionHeartbeatRequest.region:type_name -> pdpb.Region
	15, // 10: pdpb.RegionHeartbeatRequest.leader:type_name -> pdpb.Peer
	20, // 11: pdpb.RegionHeartbeatResponse.transfer_leader:type_name -> pdpb.TransferLeader
	22, // 12: pdpb.RegionHeartbeatResponse.change_peer:type_name -> pdpb.ChangePeer
	1,  // 13: pdpb.ChangePeer.change_type:type_name -> pdpb.ChangePeer.ChangeType
	15, // 14: pdpb.ChangePeer.peer:type_name -> pdpb.Peer
	16, // 15: pdpb.RegionContext.region_epoch:type_name -> pdpb.RegionEpoch
	15, // 16: pdpb.RegionContext.peer:type_name -> pdpb.Peer
	23, // 17: pdpb.PutRequest.context:type_name -> pdpb.RegionContext
	23, // 18: pdpb.GetRequest.context:type_name -> pdpb.RegionContext
	23, // 19: pdpb.DeleteRequest.context:type_name -> pdpb.RegionContext
	4,  // 20: pdpb.GetStoreResponse.store:type_name -> pdpb.MetaStore
	11, // 21: pdpb.PD.GetTS:input_type -> pdpb.GetTSRequest
	7,  // 22: pdpb.PD.PutStore:input_type -> pdpb.PutStoreRequest
	9,  // 23: pdpb.PD.StoreHeartbeat:input_type -> pdpb.StoreHeartbeatRequest
	2,  // 24: pdpb.PD.AllocID:input_type -> pdpb.AllocIDRequest
	17, // 25: pdpb.PD.GetRegion:input_type -> pdpb.GetRegionRequest
	19, // 26: pdpb.PD.RegionHeartbeat:input_type -> pdpb.RegionHeartbeatRequest
	27, // 27: pdpb.PD.GetStore:input_type -> pdpb.GetStoreRequest
	13, // 28: pdpb.PD.GetTS:output_type -> pdpb.GetTSResponse
	8,  // 29: pdpb.PD.PutStore:output_type -> pdpb.PutStoreResponse
	10, // 30: pdpb.PD.StoreHeartbeat:output_type -> pdpb.StoreHeartbeatResponse
	3,  // 31: pdpb.PD.AllocID:output_type -> pdpb.AllocIDResponse
	18, // 32: pdpb.PD.GetRegion:output_type -> pdpb.GetRegionResponse
	21, // 33: pdpb.PD.RegionHeartbeat:output_type -> pdpb.RegionHeartbeatResponse
	28, // 34: pdpb.PD.GetStore:output_type -> pdpb.GetStoreResponse
	28, // [28:35] is the sub-list for method output_type
	21, // [21:28] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_pdpb_proto_init() }
func file_pdpb_proto_init() {
	if File_pdpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pdpb_proto_rawDesc), len(file_pdpb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pdpb_proto_goTypes,
		DependencyIndexes: file_pdpb_proto_depIdxs,
		EnumInfos:         file_pdpb_proto_enumTypes,
		MessageInfos:      file_pdpb_proto_msgTypes,
	}.Build()
	File_pdpb_proto = out.File
	file_pdpb_proto_goTypes = nil
	file_pdpb_proto_depIdxs = nil
}
