// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: raft_serverpb.proto

package raft_serverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	titankvpb "titankv/api/titankvpb"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerState int32

const (
	PeerState_Normal    PeerState = 0
	PeerState_Tombstone PeerState = 1 // 标记该 Region 正在被销毁/迁移
)

// Enum value maps for PeerState.
var (
	PeerState_name = map[int32]string{
		0: "Normal",
		1: "Tombstone",
	}
	PeerState_value = map[string]int32{
		"Normal":    0,
		"Tombstone": 1,
	}
)

func (x PeerState) Enum() *PeerState {
	p := new(PeerState)
	*p = x
	return p
}

func (x PeerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerState) Descriptor() protoreflect.EnumDescriptor {
	return file_raft_serverpb_proto_enumTypes[0].Descriptor()
}

func (PeerState) Type() protoreflect.EnumType {
	return &file_raft_serverpb_proto_enumTypes[0]
}

func (x PeerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerState.Descriptor instead.
func (PeerState) EnumDescriptor() ([]byte, []int) {
	return file_raft_serverpb_proto_rawDescGZIP(), []int{0}
}

// 存储 Raft 的 HardState (Term, Vote, Commit)
// 我们直接把 etcd/raft 的 HardState 字段展开在这里，避免引入外部 proto 依赖
type RaftLocalState struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Term   uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Vote   uint64                 `protobuf:"varint,2,opt,name=vote,proto3" json:"vote,omitempty"`
	Commit uint64                 `protobuf:"varint,3,opt,name=commit,proto3" json:"commit,omitempty"`
	// 记录该 Region 最大的 Log Index
	LastIndex     uint64 `protobuf:"varint,4,opt,name=last_index,json=lastIndex,proto3" json:"last_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftLocalState) Reset() {
	*x = RaftLocalState{}
	mi := &file_raft_serverpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftLocalState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftLocalState) ProtoMessage() {}

func (x *RaftLocalState) ProtoReflect() protoreflect.Message {
	mi := &file_raft_serverpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftLocalState.ProtoReflect.Descriptor instead.
func (*RaftLocalState) Descriptor() ([]byte, []int) {
	return file_raft_serverpb_proto_rawDescGZIP(), []int{0}
}

func (x *RaftLocalState) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftLocalState) GetVote() uint64 {
	if x != nil {
		return x.Vote
	}
	return 0
}

func (x *RaftLocalState) GetCommit() uint64 {
	if x != nil {
		return x.Commit
	}
	return 0
}

func (x *RaftLocalState) GetLastIndex() uint64 {
	if x != nil {
		return x.LastIndex
	}
	return 0
}

// 记录日志截断状态 (Log Compaction)
type RaftTruncatedState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftTruncatedState) Reset() {
	*x = RaftTruncatedState{}
	mi := &file_raft_serverpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftTruncatedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftTruncatedState) ProtoMessage() {}

func (x *RaftTruncatedState) ProtoReflect() protoreflect.Message {
	mi := &file_raft_serverpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftTruncatedState.ProtoReflect.Descriptor instead.
func (*RaftTruncatedState) Descriptor() ([]byte, []int) {
	return file_raft_serverpb_proto_rawDescGZIP(), []int{1}
}

func (x *RaftTruncatedState) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RaftTruncatedState) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

// 存储应用状态 (Applied Index)
type RaftApplyState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppliedIndex   uint64                 `protobuf:"varint,1,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	TruncatedState *RaftTruncatedState    `protobuf:"bytes,2,opt,name=truncated_state,json=truncatedState,proto3" json:"truncated_state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RaftApplyState) Reset() {
	*x = RaftApplyState{}
	mi := &file_raft_serverpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftApplyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftApplyState) ProtoMessage() {}

func (x *RaftApplyState) ProtoReflect() protoreflect.Message {
	mi := &file_raft_serverpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftApplyState.ProtoReflect.Descriptor instead.
func (*RaftApplyState) Descriptor() ([]byte, []int) {
	return file_raft_serverpb_proto_rawDescGZIP(), []int{2}
}

func (x *RaftApplyState) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *RaftApplyState) GetTruncatedState() *RaftTruncatedState {
	if x != nil {
		return x.TruncatedState
	}
	return nil
}

// Region 本地状态 (包含 Region 元数据和状态)
// Key: RegionStateKey(region_id) -> Value: RegionLocalState
type RegionLocalState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         PeerState              `protobuf:"varint,1,opt,name=state,proto3,enum=raft_serverpb.PeerState" json:"state,omitempty"`
	Region        *titankvpb.Region      `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"` // 引用 titankv.proto 中的定义
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionLocalState) Reset() {
	*x = RegionLocalState{}
	mi := &file_raft_serverpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionLocalState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionLocalState) ProtoMessage() {}

func (x *RegionLocalState) ProtoReflect() protoreflect.Message {
	mi := &file_raft_serverpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionLocalState.ProtoReflect.Descriptor instead.
func (*RegionLocalState) Descriptor() ([]byte, []int) {
	return file_raft_serverpb_proto_rawDescGZIP(), []int{3}
}

func (x *RegionLocalState) GetState() PeerState {
	if x != nil {
		return x.State
	}
	return PeerState_Normal
}

func (x *RegionLocalState) GetRegion() *titankvpb.Region {
	if x != nil {
		return x.Region
	}
	return nil
}

var File_raft_serverpb_proto protoreflect.FileDescriptor

const file_raft_serverpb_proto_rawDesc = "" +
	"\n" +
	"\x13raft_serverpb.proto\x12\rraft_serverpb\x1a\rtitankv.proto\"o\n" +
	"\x0eRaftLocalState\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x12\n" +
	"\x04vote\x18\x02 \x01(\x04R\x04vote\x12\x16\n" +
	"\x06commit\x18\x03 \x01(\x04R\x06commit\x12\x1d\n" +
	"\n" +
	"last_index\x18\x04 \x01(\x04R\tlastIndex\">\n" +
	"\x12RaftTruncatedState\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\"\x81\x01\n" +
	"\x0eRaftApplyState\x12#\n" +
	"\rapplied_index\x18\x01 \x01(\x04R\fappliedIndex\x12J\n" +
	"\x0ftruncated_state\x18\x02 \x01(\v2!.raft_serverpb.RaftTruncatedStateR\x0etruncatedState\"k\n" +
	"\x10RegionLocalState\x12.\n" +
	"\x05state\x18\x01 \x01(\x0e2\x18.raft_serverpb.PeerStateR\x05state\x12'\n" +
	"\x06region\x18\x02 \x01(\v2\x0f.titankv.RegionR\x06region*&\n" +
	"\tPeerState\x12\n" +
	"\n" +
	"\x06Normal\x10\x00\x12\r\n" +
	"\tTombstone\x10\x01B\x1bZ\x19titankv/api/raft_serverpbb\x06proto3"

var (
	file_raft_serverpb_proto_rawDescOnce sync.Once
	file_raft_serverpb_proto_rawDescData []byte
)

func file_raft_serverpb_proto_rawDescGZIP() []byte {
	file_raft_serverpb_proto_rawDescOnce.Do(func() {
		file_raft_serverpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raft_serverpb_proto_rawDesc), len(file_raft_serverpb_proto_rawDesc)))
	})
	return file_raft_serverpb_proto_rawDescData
}

var file_raft_serverpb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_raft_serverpb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_raft_serverpb_proto_goTypes = []any{
	(PeerState)(0),             // 0: raft_serverpb.PeerState
	(*RaftLocalState)(nil),     // 1: raft_serverpb.RaftLocalState
	(*RaftTruncatedState)(nil), // 2: raft_serverpb.RaftTruncatedState
	(*RaftApplyState)(nil),     // 3: raft_serverpb.RaftApplyState
	(*RegionLocalState)(nil),   // 4: raft_serverpb.RegionLocalState
	(*titankvpb.Region)(nil),   // 5: titankv.Region
}
var file_raft_serverpb_proto_depIdxs = []int32{
	2, // 0: raft_serverpb.RaftApplyState.truncated_state:type_name -> raft_serverpb.RaftTruncatedState
	0, // 1: raft_serverpb.RegionLocalState.state:type_name -> raft_serverpb.PeerState
	5, // 2: raft_serverpb.RegionLocalState.region:type_name -> titankv.Region
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_raft_serverpb_proto_init() }
func file_raft_serverpb_proto_init() {
	if File_raft_serverpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raft_serverpb_proto_rawDesc), len(file_raft_serverpb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_raft_serverpb_proto_goTypes,
		DependencyIndexes: file_raft_serverpb_proto_depIdxs,
		EnumInfos:         file_raft_serverpb_proto_enumTypes,
		MessageInfos:      file_raft_serverpb_proto_msgTypes,
	}.Build()
	File_raft_serverpb_proto = out.File
	file_raft_serverpb_proto_goTypes = nil
	file_raft_serverpb_proto_depIdxs = nil
}
