// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: titankv.proto

package titankvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaftCommand_OpType int32

const (
	RaftCommand_PUT    RaftCommand_OpType = 0
	RaftCommand_DELETE RaftCommand_OpType = 1
)

// Enum value maps for RaftCommand_OpType.
var (
	RaftCommand_OpType_name = map[int32]string{
		0: "PUT",
		1: "DELETE",
	}
	RaftCommand_OpType_value = map[string]int32{
		"PUT":    0,
		"DELETE": 1,
	}
)

func (x RaftCommand_OpType) Enum() *RaftCommand_OpType {
	p := new(RaftCommand_OpType)
	*p = x
	return p
}

func (x RaftCommand_OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RaftCommand_OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_titankv_proto_enumTypes[0].Descriptor()
}

func (RaftCommand_OpType) Type() protoreflect.EnumType {
	return &file_titankv_proto_enumTypes[0]
}

func (x RaftCommand_OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RaftCommand_OpType.Descriptor instead.
func (RaftCommand_OpType) EnumDescriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{9, 0}
}

type RegionEpoch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfVer       uint64                 `protobuf:"varint,1,opt,name=conf_ver,json=confVer,proto3" json:"conf_ver,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionEpoch) Reset() {
	*x = RegionEpoch{}
	mi := &file_titankv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionEpoch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionEpoch) ProtoMessage() {}

func (x *RegionEpoch) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionEpoch.ProtoReflect.Descriptor instead.
func (*RegionEpoch) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{0}
}

func (x *RegionEpoch) GetConfVer() uint64 {
	if x != nil {
		return x.ConfVer
	}
	return 0
}

func (x *RegionEpoch) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StoreId       uint64                 `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_titankv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{1}
}

func (x *Peer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Peer) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

type RegionContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	RegionEpoch   *RegionEpoch           `protobuf:"bytes,2,opt,name=region_epoch,json=regionEpoch,proto3" json:"region_epoch,omitempty"`
	Peer          *Peer                  `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionContext) Reset() {
	*x = RegionContext{}
	mi := &file_titankv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionContext) ProtoMessage() {}

func (x *RegionContext) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionContext.ProtoReflect.Descriptor instead.
func (*RegionContext) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{2}
}

func (x *RegionContext) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *RegionContext) GetRegionEpoch() *RegionEpoch {
	if x != nil {
		return x.RegionEpoch
	}
	return nil
}

func (x *RegionContext) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RegionContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // 【新增】
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_titankv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetContext() *RegionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_titankv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RegionContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // 【新增】
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_titankv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{5}
}

func (x *PutRequest) GetContext() *RegionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       int32                  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	LeaderId      uint64                 `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_titankv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{6}
}

func (x *PutResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *PutResponse) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RegionContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // 【新增】
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_titankv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetContext() *RegionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       int32                  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	LeaderId      uint64                 `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_titankv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *DeleteResponse) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type RaftCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            RaftCommand_OpType     `protobuf:"varint,1,opt,name=op,proto3,enum=titankv.RaftCommand_OpType" json:"op,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftCommand) Reset() {
	*x = RaftCommand{}
	mi := &file_titankv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftCommand) ProtoMessage() {}

func (x *RaftCommand) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftCommand.ProtoReflect.Descriptor instead.
func (*RaftCommand) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{9}
}

func (x *RaftCommand) GetOp() RaftCommand_OpType {
	if x != nil {
		return x.Op
	}
	return RaftCommand_PUT
}

func (x *RaftCommand) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RaftCommand) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type BatchRaftCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*RaftCommand         `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRaftCommand) Reset() {
	*x = BatchRaftCommand{}
	mi := &file_titankv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRaftCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRaftCommand) ProtoMessage() {}

func (x *BatchRaftCommand) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRaftCommand.ProtoReflect.Descriptor instead.
func (*BatchRaftCommand) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{10}
}

func (x *BatchRaftCommand) GetCommands() []*RaftCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type RaftMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 直接传输序列化后的 etcd/raft/raftpb.Message
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessage) Reset() {
	*x = RaftMessage{}
	mi := &file_titankv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessage) ProtoMessage() {}

func (x *RaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessage.ProtoReflect.Descriptor instead.
func (*RaftMessage) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{11}
}

func (x *RaftMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RaftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftResponse) Reset() {
	*x = RaftResponse{}
	mi := &file_titankv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftResponse) ProtoMessage() {}

func (x *RaftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftResponse.ProtoReflect.Descriptor instead.
func (*RaftResponse) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{12}
}

type UpdateConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 如果 > 0 则更新，否则忽略
	GcThreshold   float64 `protobuf:"fixed64,1,opt,name=gc_threshold,json=gcThreshold,proto3" json:"gc_threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_titankv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateConfigRequest) GetGcThreshold() float64 {
	if x != nil {
		return x.GcThreshold
	}
	return 0
}

type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_titankv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{14}
}

var File_titankv_proto protoreflect.FileDescriptor

const file_titankv_proto_rawDesc = "" +
	"\n" +
	"\rtitankv.proto\x12\atitankv\"B\n" +
	"\vRegionEpoch\x12\x19\n" +
	"\bconf_ver\x18\x01 \x01(\x04R\aconfVer\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"1\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\x04R\astoreId\"\x88\x01\n" +
	"\rRegionContext\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x127\n" +
	"\fregion_epoch\x18\x02 \x01(\v2\x14.titankv.RegionEpochR\vregionEpoch\x12!\n" +
	"\x04peer\x18\x03 \x01(\v2\r.titankv.PeerR\x04peer\"P\n" +
	"\n" +
	"GetRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.titankv.RegionContextR\acontext\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"f\n" +
	"\n" +
	"PutRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.titankv.RegionContextR\acontext\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"E\n" +
	"\vPutResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x04R\bleaderId\"S\n" +
	"\rDeleteRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.titankv.RegionContextR\acontext\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"H\n" +
	"\x0eDeleteResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x04R\bleaderId\"\x81\x01\n" +
	"\vRaftCommand\x12+\n" +
	"\x02op\x18\x01 \x01(\x0e2\x1b.titankv.RaftCommand.OpTypeR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"\x1d\n" +
	"\x06OpType\x12\a\n" +
	"\x03PUT\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\"D\n" +
	"\x10BatchRaftCommand\x120\n" +
	"\bcommands\x18\x01 \x03(\v2\x14.titankv.RaftCommandR\bcommands\"!\n" +
	"\vRaftMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x0e\n" +
	"\fRaftResponse\"8\n" +
	"\x13UpdateConfigRequest\x12!\n" +
	"\fgc_threshold\x18\x01 \x01(\x01R\vgcThreshold\"\x16\n" +
	"\x14UpdateConfigResponse2\xaa\x02\n" +
	"\aTitanKV\x120\n" +
	"\x03Get\x12\x13.titankv.GetRequest\x1a\x14.titankv.GetResponse\x120\n" +
	"\x03Put\x12\x13.titankv.PutRequest\x1a\x14.titankv.PutResponse\x129\n" +
	"\x06Delete\x12\x16.titankv.DeleteRequest\x1a\x17.titankv.DeleteResponse\x123\n" +
	"\x04Raft\x12\x14.titankv.RaftMessage\x1a\x15.titankv.RaftResponse\x12K\n" +
	"\fUpdateConfig\x12\x1c.titankv.UpdateConfigRequest\x1a\x1d.titankv.UpdateConfigResponseB\x17Z\x15titankv/api/titankvpbb\x06proto3"

var (
	file_titankv_proto_rawDescOnce sync.Once
	file_titankv_proto_rawDescData []byte
)

func file_titankv_proto_rawDescGZIP() []byte {
	file_titankv_proto_rawDescOnce.Do(func() {
		file_titankv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_titankv_proto_rawDesc), len(file_titankv_proto_rawDesc)))
	})
	return file_titankv_proto_rawDescData
}

var file_titankv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_titankv_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_titankv_proto_goTypes = []any{
	(RaftCommand_OpType)(0),      // 0: titankv.RaftCommand.OpType
	(*RegionEpoch)(nil),          // 1: titankv.RegionEpoch
	(*Peer)(nil),                 // 2: titankv.Peer
	(*RegionContext)(nil),        // 3: titankv.RegionContext
	(*GetRequest)(nil),           // 4: titankv.GetRequest
	(*GetResponse)(nil),          // 5: titankv.GetResponse
	(*PutRequest)(nil),           // 6: titankv.PutRequest
	(*PutResponse)(nil),          // 7: titankv.PutResponse
	(*DeleteRequest)(nil),        // 8: titankv.DeleteRequest
	(*DeleteResponse)(nil),       // 9: titankv.DeleteResponse
	(*RaftCommand)(nil),          // 10: titankv.RaftCommand
	(*BatchRaftCommand)(nil),     // 11: titankv.BatchRaftCommand
	(*RaftMessage)(nil),          // 12: titankv.RaftMessage
	(*RaftResponse)(nil),         // 13: titankv.RaftResponse
	(*UpdateConfigRequest)(nil),  // 14: titankv.UpdateConfigRequest
	(*UpdateConfigResponse)(nil), // 15: titankv.UpdateConfigResponse
}
var file_titankv_proto_depIdxs = []int32{
	1,  // 0: titankv.RegionContext.region_epoch:type_name -> titankv.RegionEpoch
	2,  // 1: titankv.RegionContext.peer:type_name -> titankv.Peer
	3,  // 2: titankv.GetRequest.context:type_name -> titankv.RegionContext
	3,  // 3: titankv.PutRequest.context:type_name -> titankv.RegionContext
	3,  // 4: titankv.DeleteRequest.context:type_name -> titankv.RegionContext
	0,  // 5: titankv.RaftCommand.op:type_name -> titankv.RaftCommand.OpType
	10, // 6: titankv.BatchRaftCommand.commands:type_name -> titankv.RaftCommand
	4,  // 7: titankv.TitanKV.Get:input_type -> titankv.GetRequest
	6,  // 8: titankv.TitanKV.Put:input_type -> titankv.PutRequest
	8,  // 9: titankv.TitanKV.Delete:input_type -> titankv.DeleteRequest
	12, // 10: titankv.TitanKV.Raft:input_type -> titankv.RaftMessage
	14, // 11: titankv.TitanKV.UpdateConfig:input_type -> titankv.UpdateConfigRequest
	5,  // 12: titankv.TitanKV.Get:output_type -> titankv.GetResponse
	7,  // 13: titankv.TitanKV.Put:output_type -> titankv.PutResponse
	9,  // 14: titankv.TitanKV.Delete:output_type -> titankv.DeleteResponse
	13, // 15: titankv.TitanKV.Raft:output_type -> titankv.RaftResponse
	15, // 16: titankv.TitanKV.UpdateConfig:output_type -> titankv.UpdateConfigResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_titankv_proto_init() }
func file_titankv_proto_init() {
	if File_titankv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_titankv_proto_rawDesc), len(file_titankv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_titankv_proto_goTypes,
		DependencyIndexes: file_titankv_proto_depIdxs,
		EnumInfos:         file_titankv_proto_enumTypes,
		MessageInfos:      file_titankv_proto_msgTypes,
	}.Build()
	File_titankv_proto = out.File
	file_titankv_proto_goTypes = nil
	file_titankv_proto_depIdxs = nil
}
