// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: titankv.proto

package titankvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangePeer_ChangeType int32

const (
	ChangePeer_ADD_NODE    ChangePeer_ChangeType = 0
	ChangePeer_REMOVE_NODE ChangePeer_ChangeType = 1
)

// Enum value maps for ChangePeer_ChangeType.
var (
	ChangePeer_ChangeType_name = map[int32]string{
		0: "ADD_NODE",
		1: "REMOVE_NODE",
	}
	ChangePeer_ChangeType_value = map[string]int32{
		"ADD_NODE":    0,
		"REMOVE_NODE": 1,
	}
)

func (x ChangePeer_ChangeType) Enum() *ChangePeer_ChangeType {
	p := new(ChangePeer_ChangeType)
	*p = x
	return p
}

func (x ChangePeer_ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangePeer_ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_titankv_proto_enumTypes[0].Descriptor()
}

func (ChangePeer_ChangeType) Type() protoreflect.EnumType {
	return &file_titankv_proto_enumTypes[0]
}

func (x ChangePeer_ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangePeer_ChangeType.Descriptor instead.
func (ChangePeer_ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{2, 0}
}

type Mutation_Op int32

const (
	Mutation_Put    Mutation_Op = 0
	Mutation_Delete Mutation_Op = 1
	Mutation_Lock   Mutation_Op = 2
)

// Enum value maps for Mutation_Op.
var (
	Mutation_Op_name = map[int32]string{
		0: "Put",
		1: "Delete",
		2: "Lock",
	}
	Mutation_Op_value = map[string]int32{
		"Put":    0,
		"Delete": 1,
		"Lock":   2,
	}
)

func (x Mutation_Op) Enum() *Mutation_Op {
	p := new(Mutation_Op)
	*p = x
	return p
}

func (x Mutation_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mutation_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_titankv_proto_enumTypes[1].Descriptor()
}

func (Mutation_Op) Type() protoreflect.EnumType {
	return &file_titankv_proto_enumTypes[1]
}

func (x Mutation_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mutation_Op.Descriptor instead.
func (Mutation_Op) EnumDescriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{7, 0}
}

type RaftCommand_CmdType int32

const (
	RaftCommand_NORMAL RaftCommand_CmdType = 0 // Put, Delete
	RaftCommand_ADMIN  RaftCommand_CmdType = 1 // Split, Compact, ConfChange
)

// Enum value maps for RaftCommand_CmdType.
var (
	RaftCommand_CmdType_name = map[int32]string{
		0: "NORMAL",
		1: "ADMIN",
	}
	RaftCommand_CmdType_value = map[string]int32{
		"NORMAL": 0,
		"ADMIN":  1,
	}
)

func (x RaftCommand_CmdType) Enum() *RaftCommand_CmdType {
	p := new(RaftCommand_CmdType)
	*p = x
	return p
}

func (x RaftCommand_CmdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RaftCommand_CmdType) Descriptor() protoreflect.EnumDescriptor {
	return file_titankv_proto_enumTypes[2].Descriptor()
}

func (RaftCommand_CmdType) Type() protoreflect.EnumType {
	return &file_titankv_proto_enumTypes[2]
}

func (x RaftCommand_CmdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RaftCommand_CmdType.Descriptor instead.
func (RaftCommand_CmdType) EnumDescriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{21, 0}
}

type RaftCommand_OpType int32

const (
	RaftCommand_PUT    RaftCommand_OpType = 0
	RaftCommand_DELETE RaftCommand_OpType = 1
)

// Enum value maps for RaftCommand_OpType.
var (
	RaftCommand_OpType_name = map[int32]string{
		0: "PUT",
		1: "DELETE",
	}
	RaftCommand_OpType_value = map[string]int32{
		"PUT":    0,
		"DELETE": 1,
	}
)

func (x RaftCommand_OpType) Enum() *RaftCommand_OpType {
	p := new(RaftCommand_OpType)
	*p = x
	return p
}

func (x RaftCommand_OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RaftCommand_OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_titankv_proto_enumTypes[3].Descriptor()
}

func (RaftCommand_OpType) Type() protoreflect.EnumType {
	return &file_titankv_proto_enumTypes[3]
}

func (x RaftCommand_OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RaftCommand_OpType.Descriptor instead.
func (RaftCommand_OpType) EnumDescriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{21, 1}
}

type AdminRequest_AdminCmdType int32

const (
	AdminRequest_SPLIT       AdminRequest_AdminCmdType = 0
	AdminRequest_COMPACT     AdminRequest_AdminCmdType = 1
	AdminRequest_CONF_CHANGE AdminRequest_AdminCmdType = 2
)

// Enum value maps for AdminRequest_AdminCmdType.
var (
	AdminRequest_AdminCmdType_name = map[int32]string{
		0: "SPLIT",
		1: "COMPACT",
		2: "CONF_CHANGE",
	}
	AdminRequest_AdminCmdType_value = map[string]int32{
		"SPLIT":       0,
		"COMPACT":     1,
		"CONF_CHANGE": 2,
	}
)

func (x AdminRequest_AdminCmdType) Enum() *AdminRequest_AdminCmdType {
	p := new(AdminRequest_AdminCmdType)
	*p = x
	return p
}

func (x AdminRequest_AdminCmdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminRequest_AdminCmdType) Descriptor() protoreflect.EnumDescriptor {
	return file_titankv_proto_enumTypes[4].Descriptor()
}

func (AdminRequest_AdminCmdType) Type() protoreflect.EnumType {
	return &file_titankv_proto_enumTypes[4]
}

func (x AdminRequest_AdminCmdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminRequest_AdminCmdType.Descriptor instead.
func (AdminRequest_AdminCmdType) EnumDescriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{22, 0}
}

type RegionEpoch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfVer       uint64                 `protobuf:"varint,1,opt,name=conf_ver,json=confVer,proto3" json:"conf_ver,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionEpoch) Reset() {
	*x = RegionEpoch{}
	mi := &file_titankv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionEpoch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionEpoch) ProtoMessage() {}

func (x *RegionEpoch) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionEpoch.ProtoReflect.Descriptor instead.
func (*RegionEpoch) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{0}
}

func (x *RegionEpoch) GetConfVer() uint64 {
	if x != nil {
		return x.ConfVer
	}
	return 0
}

func (x *RegionEpoch) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StoreId       uint64                 `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_titankv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{1}
}

func (x *Peer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Peer) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

type ChangePeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeType    ChangePeer_ChangeType  `protobuf:"varint,1,opt,name=change_type,json=changeType,proto3,enum=titankv.ChangePeer_ChangeType" json:"change_type,omitempty"`
	Peer          *Peer                  `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePeer) Reset() {
	*x = ChangePeer{}
	mi := &file_titankv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePeer) ProtoMessage() {}

func (x *ChangePeer) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePeer.ProtoReflect.Descriptor instead.
func (*ChangePeer) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{2}
}

func (x *ChangePeer) GetChangeType() ChangePeer_ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ChangePeer_ADD_NODE
}

func (x *ChangePeer) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type Region struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartKey      []byte                 `protobuf:"bytes,2,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        []byte                 `protobuf:"bytes,3,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	RegionEpoch   *RegionEpoch           `protobuf:"bytes,4,opt,name=region_epoch,json=regionEpoch,proto3" json:"region_epoch,omitempty"`
	Peers         []*Peer                `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_titankv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{3}
}

func (x *Region) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Region) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *Region) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *Region) GetRegionEpoch() *RegionEpoch {
	if x != nil {
		return x.RegionEpoch
	}
	return nil
}

func (x *Region) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type RegionContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	RegionEpoch   *RegionEpoch           `protobuf:"bytes,2,opt,name=region_epoch,json=regionEpoch,proto3" json:"region_epoch,omitempty"`
	Peer          *Peer                  `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionContext) Reset() {
	*x = RegionContext{}
	mi := &file_titankv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionContext) ProtoMessage() {}

func (x *RegionContext) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionContext.ProtoReflect.Descriptor instead.
func (*RegionContext) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{4}
}

func (x *RegionContext) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *RegionContext) GetRegionEpoch() *RegionEpoch {
	if x != nil {
		return x.RegionEpoch
	}
	return nil
}

func (x *RegionContext) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type SnapshotChunk struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RegionId uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	// 整个文件的元数据
	FileSize uint64 `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Checksum uint64 `protobuf:"varint,3,opt,name=checksum,proto3" json:"checksum,omitempty"` // CRC32
	// 当前块
	Offset           uint64 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Data             []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	IsLast           bool   `protobuf:"varint,6,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"` // 是否最后一块
	RaftSnapshotData []byte `protobuf:"bytes,7,opt,name=raft_snapshot_data,json=raftSnapshotData,proto3" json:"raft_snapshot_data,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SnapshotChunk) Reset() {
	*x = SnapshotChunk{}
	mi := &file_titankv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotChunk) ProtoMessage() {}

func (x *SnapshotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotChunk.ProtoReflect.Descriptor instead.
func (*SnapshotChunk) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{5}
}

func (x *SnapshotChunk) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *SnapshotChunk) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *SnapshotChunk) GetChecksum() uint64 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *SnapshotChunk) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SnapshotChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SnapshotChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *SnapshotChunk) GetRaftSnapshotData() []byte {
	if x != nil {
		return x.RaftSnapshotData
	}
	return nil
}

type PrewriteRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Context *RegionContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	// 批处理多个 Mutation
	Mutations []*Mutation `protobuf:"bytes,2,rep,name=mutations,proto3" json:"mutations,omitempty"`
	// 事务开始时间
	StartTs uint64 `protobuf:"varint,3,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	// Primary Key (用于故障恢复)
	PrimaryKey    []byte `protobuf:"bytes,4,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	LockTtl       uint64 `protobuf:"varint,5,opt,name=lock_ttl,json=lockTtl,proto3" json:"lock_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrewriteRequest) Reset() {
	*x = PrewriteRequest{}
	mi := &file_titankv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrewriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrewriteRequest) ProtoMessage() {}

func (x *PrewriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrewriteRequest.ProtoReflect.Descriptor instead.
func (*PrewriteRequest) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{6}
}

func (x *PrewriteRequest) GetContext() *RegionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *PrewriteRequest) GetMutations() []*Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

func (x *PrewriteRequest) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *PrewriteRequest) GetPrimaryKey() []byte {
	if x != nil {
		return x.PrimaryKey
	}
	return nil
}

func (x *PrewriteRequest) GetLockTtl() uint64 {
	if x != nil {
		return x.LockTtl
	}
	return 0
}

type Mutation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            Mutation_Op            `protobuf:"varint,1,opt,name=op,proto3,enum=titankv.Mutation_Op" json:"op,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_titankv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{7}
}

func (x *Mutation) GetOp() Mutation_Op {
	if x != nil {
		return x.Op
	}
	return Mutation_Put
}

func (x *Mutation) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Mutation) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PrewriteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 错误信息
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // 空表示成功
	// 如果有 Write Conflict
	Conflict *WriteConflict `protobuf:"bytes,2,opt,name=conflict,proto3" json:"conflict,omitempty"`
	// 如果有 KeyLocked
	KeyError      *KeyError `protobuf:"bytes,3,opt,name=key_error,json=keyError,proto3" json:"key_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrewriteResponse) Reset() {
	*x = PrewriteResponse{}
	mi := &file_titankv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrewriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrewriteResponse) ProtoMessage() {}

func (x *PrewriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrewriteResponse.ProtoReflect.Descriptor instead.
func (*PrewriteResponse) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{8}
}

func (x *PrewriteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PrewriteResponse) GetConflict() *WriteConflict {
	if x != nil {
		return x.Conflict
	}
	return nil
}

func (x *PrewriteResponse) GetKeyError() *KeyError {
	if x != nil {
		return x.KeyError
	}
	return nil
}

type WriteConflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTs       uint64                 `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	ConflictTs    uint64                 `protobuf:"varint,2,opt,name=conflict_ts,json=conflictTs,proto3" json:"conflict_ts,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Primary       []byte                 `protobuf:"bytes,4,opt,name=primary,proto3" json:"primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteConflict) Reset() {
	*x = WriteConflict{}
	mi := &file_titankv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConflict) ProtoMessage() {}

func (x *WriteConflict) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConflict.ProtoReflect.Descriptor instead.
func (*WriteConflict) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{9}
}

func (x *WriteConflict) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *WriteConflict) GetConflictTs() uint64 {
	if x != nil {
		return x.ConflictTs
	}
	return 0
}

func (x *WriteConflict) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *WriteConflict) GetPrimary() []byte {
	if x != nil {
		return x.Primary
	}
	return nil
}

type KeyError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// 锁信息
	LockInfo      *LockInfo `protobuf:"bytes,2,opt,name=lock_info,json=lockInfo,proto3" json:"lock_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyError) Reset() {
	*x = KeyError{}
	mi := &file_titankv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyError) ProtoMessage() {}

func (x *KeyError) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyError.ProtoReflect.Descriptor instead.
func (*KeyError) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{10}
}

func (x *KeyError) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyError) GetLockInfo() *LockInfo {
	if x != nil {
		return x.LockInfo
	}
	return nil
}

type LockInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrimaryLock   []byte                 `protobuf:"bytes,1,opt,name=primary_lock,json=primaryLock,proto3" json:"primary_lock,omitempty"`
	LockVersion   uint64                 `protobuf:"varint,2,opt,name=lock_version,json=lockVersion,proto3" json:"lock_version,omitempty"`
	Ttl           uint64                 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockInfo) Reset() {
	*x = LockInfo{}
	mi := &file_titankv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockInfo) ProtoMessage() {}

func (x *LockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockInfo.ProtoReflect.Descriptor instead.
func (*LockInfo) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{11}
}

func (x *LockInfo) GetPrimaryLock() []byte {
	if x != nil {
		return x.PrimaryLock
	}
	return nil
}

func (x *LockInfo) GetLockVersion() uint64 {
	if x != nil {
		return x.LockVersion
	}
	return 0
}

func (x *LockInfo) GetTtl() uint64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RegionContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	StartTs       uint64                 `protobuf:"varint,2,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	CommitTs      uint64                 `protobuf:"varint,3,opt,name=commit_ts,json=commitTs,proto3" json:"commit_ts,omitempty"`
	Keys          [][]byte               `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_titankv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{12}
}

func (x *CommitRequest) GetContext() *RegionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CommitRequest) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *CommitRequest) GetCommitTs() uint64 {
	if x != nil {
		return x.CommitTs
	}
	return 0
}

func (x *CommitRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_titankv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{13}
}

func (x *CommitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RegionContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // 【新增】
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	StartTs       uint64                 `protobuf:"varint,3,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_titankv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{14}
}

func (x *GetRequest) GetContext() *RegionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetRequest) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_titankv_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{15}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RegionContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // 【新增】
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_titankv_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{16}
}

func (x *PutRequest) GetContext() *RegionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       int32                  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	LeaderId      uint64                 `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_titankv_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{17}
}

func (x *PutResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *PutResponse) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RegionContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // 【新增】
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_titankv_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteRequest) GetContext() *RegionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       int32                  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	LeaderId      uint64                 `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_titankv_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *DeleteResponse) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type RaftRequestHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	RegionEpoch   *RegionEpoch           `protobuf:"bytes,2,opt,name=region_epoch,json=regionEpoch,proto3" json:"region_epoch,omitempty"`
	Peer          *Peer                  `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftRequestHeader) Reset() {
	*x = RaftRequestHeader{}
	mi := &file_titankv_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftRequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftRequestHeader) ProtoMessage() {}

func (x *RaftRequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftRequestHeader.ProtoReflect.Descriptor instead.
func (*RaftRequestHeader) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{20}
}

func (x *RaftRequestHeader) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *RaftRequestHeader) GetRegionEpoch() *RegionEpoch {
	if x != nil {
		return x.RegionEpoch
	}
	return nil
}

func (x *RaftRequestHeader) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type RaftCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RaftRequestHeader     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Type          RaftCommand_CmdType    `protobuf:"varint,2,opt,name=type,proto3,enum=titankv.RaftCommand_CmdType" json:"type,omitempty"`
	Op            RaftCommand_OpType     `protobuf:"varint,3,opt,name=op,proto3,enum=titankv.RaftCommand_OpType" json:"op,omitempty"`
	Key           []byte                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"` // ----------------
	AdminRequest  *AdminRequest          `protobuf:"bytes,6,opt,name=admin_request,json=adminRequest,proto3" json:"admin_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftCommand) Reset() {
	*x = RaftCommand{}
	mi := &file_titankv_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftCommand) ProtoMessage() {}

func (x *RaftCommand) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftCommand.ProtoReflect.Descriptor instead.
func (*RaftCommand) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{21}
}

func (x *RaftCommand) GetHeader() *RaftRequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RaftCommand) GetType() RaftCommand_CmdType {
	if x != nil {
		return x.Type
	}
	return RaftCommand_NORMAL
}

func (x *RaftCommand) GetOp() RaftCommand_OpType {
	if x != nil {
		return x.Op
	}
	return RaftCommand_PUT
}

func (x *RaftCommand) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RaftCommand) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RaftCommand) GetAdminRequest() *AdminRequest {
	if x != nil {
		return x.AdminRequest
	}
	return nil
}

type AdminRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	CmdType       AdminRequest_AdminCmdType `protobuf:"varint,1,opt,name=cmd_type,json=cmdType,proto3,enum=titankv.AdminRequest_AdminCmdType" json:"cmd_type,omitempty"`
	Split         *SplitRequest             `protobuf:"bytes,2,opt,name=split,proto3" json:"split,omitempty"`
	ChangePeer    *ChangePeer               `protobuf:"bytes,3,opt,name=change_peer,json=changePeer,proto3" json:"change_peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRequest) Reset() {
	*x = AdminRequest{}
	mi := &file_titankv_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRequest) ProtoMessage() {}

func (x *AdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRequest.ProtoReflect.Descriptor instead.
func (*AdminRequest) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{22}
}

func (x *AdminRequest) GetCmdType() AdminRequest_AdminCmdType {
	if x != nil {
		return x.CmdType
	}
	return AdminRequest_SPLIT
}

func (x *AdminRequest) GetSplit() *SplitRequest {
	if x != nil {
		return x.Split
	}
	return nil
}

func (x *AdminRequest) GetChangePeer() *ChangePeer {
	if x != nil {
		return x.ChangePeer
	}
	return nil
}

type SplitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分裂点 Key (Encoded or User Key? 通常用 Encoded Data Key)
	SplitKey []byte `protobuf:"bytes,1,opt,name=split_key,json=splitKey,proto3" json:"split_key,omitempty"`
	// 新分裂出来的 Region ID
	NewRegionId uint64 `protobuf:"varint,2,opt,name=new_region_id,json=newRegionId,proto3" json:"new_region_id,omitempty"`
	// 新 Region 在各个 Store 上的 Peer ID
	// repeated uint64 new_peer_ids = 3;
	NewPeers      []*Peer `protobuf:"bytes,4,rep,name=new_peers,json=newPeers,proto3" json:"new_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitRequest) Reset() {
	*x = SplitRequest{}
	mi := &file_titankv_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitRequest) ProtoMessage() {}

func (x *SplitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitRequest.ProtoReflect.Descriptor instead.
func (*SplitRequest) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{23}
}

func (x *SplitRequest) GetSplitKey() []byte {
	if x != nil {
		return x.SplitKey
	}
	return nil
}

func (x *SplitRequest) GetNewRegionId() uint64 {
	if x != nil {
		return x.NewRegionId
	}
	return 0
}

func (x *SplitRequest) GetNewPeers() []*Peer {
	if x != nil {
		return x.NewPeers
	}
	return nil
}

type BatchRaftCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*RaftCommand         `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRaftCommand) Reset() {
	*x = BatchRaftCommand{}
	mi := &file_titankv_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRaftCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRaftCommand) ProtoMessage() {}

func (x *BatchRaftCommand) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRaftCommand.ProtoReflect.Descriptor instead.
func (*BatchRaftCommand) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{24}
}

func (x *BatchRaftCommand) GetCommands() []*RaftCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type RaftMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`         // 接收端的 RegionID
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                  // 实际的 raftpb.Message 序列化数据
	ToPeerId      uint64                 `protobuf:"varint,3,opt,name=to_peer_id,json=toPeerId,proto3" json:"to_peer_id,omitempty"`       // 接收端的 PeerID (用于路由到正确的 RawNode)
	FromPeerId    uint64                 `protobuf:"varint,4,opt,name=from_peer_id,json=fromPeerId,proto3" json:"from_peer_id,omitempty"` // 发送端的 PeerID
	ToStoreId     uint64                 `protobuf:"varint,5,opt,name=to_store_id,json=toStoreId,proto3" json:"to_store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessage) Reset() {
	*x = RaftMessage{}
	mi := &file_titankv_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessage) ProtoMessage() {}

func (x *RaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessage.ProtoReflect.Descriptor instead.
func (*RaftMessage) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{25}
}

func (x *RaftMessage) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *RaftMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RaftMessage) GetToPeerId() uint64 {
	if x != nil {
		return x.ToPeerId
	}
	return 0
}

func (x *RaftMessage) GetFromPeerId() uint64 {
	if x != nil {
		return x.FromPeerId
	}
	return 0
}

func (x *RaftMessage) GetToStoreId() uint64 {
	if x != nil {
		return x.ToStoreId
	}
	return 0
}

type BatchRaftMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msgs          []*RaftMessage         `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRaftMessage) Reset() {
	*x = BatchRaftMessage{}
	mi := &file_titankv_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRaftMessage) ProtoMessage() {}

func (x *BatchRaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRaftMessage.ProtoReflect.Descriptor instead.
func (*BatchRaftMessage) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{26}
}

func (x *BatchRaftMessage) GetMsgs() []*RaftMessage {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type RaftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftResponse) Reset() {
	*x = RaftResponse{}
	mi := &file_titankv_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftResponse) ProtoMessage() {}

func (x *RaftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftResponse.ProtoReflect.Descriptor instead.
func (*RaftResponse) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{27}
}

type RaftLocalState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Vote          uint64                 `protobuf:"varint,2,opt,name=vote,proto3" json:"vote,omitempty"`
	Commit        uint64                 `protobuf:"varint,3,opt,name=commit,proto3" json:"commit,omitempty"`
	LastIndex     uint64                 `protobuf:"varint,4,opt,name=last_index,json=lastIndex,proto3" json:"last_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftLocalState) Reset() {
	*x = RaftLocalState{}
	mi := &file_titankv_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftLocalState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftLocalState) ProtoMessage() {}

func (x *RaftLocalState) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftLocalState.ProtoReflect.Descriptor instead.
func (*RaftLocalState) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{28}
}

func (x *RaftLocalState) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftLocalState) GetVote() uint64 {
	if x != nil {
		return x.Vote
	}
	return 0
}

func (x *RaftLocalState) GetCommit() uint64 {
	if x != nil {
		return x.Commit
	}
	return 0
}

func (x *RaftLocalState) GetLastIndex() uint64 {
	if x != nil {
		return x.LastIndex
	}
	return 0
}

// 本地 Apply 状态
type RaftApplyState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppliedIndex   uint64                 `protobuf:"varint,1,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	TruncatedState *RaftTruncatedState    `protobuf:"bytes,2,opt,name=truncated_state,json=truncatedState,proto3" json:"truncated_state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RaftApplyState) Reset() {
	*x = RaftApplyState{}
	mi := &file_titankv_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftApplyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftApplyState) ProtoMessage() {}

func (x *RaftApplyState) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftApplyState.ProtoReflect.Descriptor instead.
func (*RaftApplyState) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{29}
}

func (x *RaftApplyState) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *RaftApplyState) GetTruncatedState() *RaftTruncatedState {
	if x != nil {
		return x.TruncatedState
	}
	return nil
}

type RaftTruncatedState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftTruncatedState) Reset() {
	*x = RaftTruncatedState{}
	mi := &file_titankv_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftTruncatedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftTruncatedState) ProtoMessage() {}

func (x *RaftTruncatedState) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftTruncatedState.ProtoReflect.Descriptor instead.
func (*RaftTruncatedState) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{30}
}

func (x *RaftTruncatedState) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RaftTruncatedState) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type UpdateConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 如果 > 0 则更新，否则忽略
	GcThreshold   float64 `protobuf:"fixed64,1,opt,name=gc_threshold,json=gcThreshold,proto3" json:"gc_threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_titankv_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateConfigRequest) GetGcThreshold() float64 {
	if x != nil {
		return x.GcThreshold
	}
	return 0
}

type RaftSnapshotMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	ConfState     *RaftConfState         `protobuf:"bytes,3,opt,name=conf_state,json=confState,proto3" json:"conf_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftSnapshotMetadata) Reset() {
	*x = RaftSnapshotMetadata{}
	mi := &file_titankv_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftSnapshotMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftSnapshotMetadata) ProtoMessage() {}

func (x *RaftSnapshotMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftSnapshotMetadata.ProtoReflect.Descriptor instead.
func (*RaftSnapshotMetadata) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{32}
}

func (x *RaftSnapshotMetadata) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RaftSnapshotMetadata) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftSnapshotMetadata) GetConfState() *RaftConfState {
	if x != nil {
		return x.ConfState
	}
	return nil
}

type RaftConfState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voters        []uint64               `protobuf:"varint,1,rep,packed,name=voters,proto3" json:"voters,omitempty"`
	Learners      []uint64               `protobuf:"varint,2,rep,packed,name=learners,proto3" json:"learners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftConfState) Reset() {
	*x = RaftConfState{}
	mi := &file_titankv_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftConfState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftConfState) ProtoMessage() {}

func (x *RaftConfState) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftConfState.ProtoReflect.Descriptor instead.
func (*RaftConfState) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{33}
}

func (x *RaftConfState) GetVoters() []uint64 {
	if x != nil {
		return x.Voters
	}
	return nil
}

func (x *RaftConfState) GetLearners() []uint64 {
	if x != nil {
		return x.Learners
	}
	return nil
}

type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_titankv_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titankv_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_titankv_proto_rawDescGZIP(), []int{34}
}

var File_titankv_proto protoreflect.FileDescriptor

const file_titankv_proto_rawDesc = "" +
	"\n" +
	"\rtitankv.proto\x12\atitankv\"B\n" +
	"\vRegionEpoch\x12\x19\n" +
	"\bconf_ver\x18\x01 \x01(\x04R\aconfVer\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"1\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\x04R\astoreId\"\x9d\x01\n" +
	"\n" +
	"ChangePeer\x12?\n" +
	"\vchange_type\x18\x01 \x01(\x0e2\x1e.titankv.ChangePeer.ChangeTypeR\n" +
	"changeType\x12!\n" +
	"\x04peer\x18\x02 \x01(\v2\r.titankv.PeerR\x04peer\"+\n" +
	"\n" +
	"ChangeType\x12\f\n" +
	"\bADD_NODE\x10\x00\x12\x0f\n" +
	"\vREMOVE_NODE\x10\x01\"\xac\x01\n" +
	"\x06Region\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tstart_key\x18\x02 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x03 \x01(\fR\x06endKey\x127\n" +
	"\fregion_epoch\x18\x04 \x01(\v2\x14.titankv.RegionEpochR\vregionEpoch\x12#\n" +
	"\x05peers\x18\x05 \x03(\v2\r.titankv.PeerR\x05peers\"\x88\x01\n" +
	"\rRegionContext\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x127\n" +
	"\fregion_epoch\x18\x02 \x01(\v2\x14.titankv.RegionEpochR\vregionEpoch\x12!\n" +
	"\x04peer\x18\x03 \x01(\v2\r.titankv.PeerR\x04peer\"\xd8\x01\n" +
	"\rSnapshotChunk\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x04R\bfileSize\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\x04R\bchecksum\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x17\n" +
	"\ais_last\x18\x06 \x01(\bR\x06isLast\x12,\n" +
	"\x12raft_snapshot_data\x18\a \x01(\fR\x10raftSnapshotData\"\xcb\x01\n" +
	"\x0fPrewriteRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.titankv.RegionContextR\acontext\x12/\n" +
	"\tmutations\x18\x02 \x03(\v2\x11.titankv.MutationR\tmutations\x12\x19\n" +
	"\bstart_ts\x18\x03 \x01(\x04R\astartTs\x12\x1f\n" +
	"\vprimary_key\x18\x04 \x01(\fR\n" +
	"primaryKey\x12\x19\n" +
	"\block_ttl\x18\x05 \x01(\x04R\alockTtl\"}\n" +
	"\bMutation\x12$\n" +
	"\x02op\x18\x01 \x01(\x0e2\x14.titankv.Mutation.OpR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"#\n" +
	"\x02Op\x12\a\n" +
	"\x03Put\x10\x00\x12\n" +
	"\n" +
	"\x06Delete\x10\x01\x12\b\n" +
	"\x04Lock\x10\x02\"\x8c\x01\n" +
	"\x10PrewriteResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x122\n" +
	"\bconflict\x18\x02 \x01(\v2\x16.titankv.WriteConflictR\bconflict\x12.\n" +
	"\tkey_error\x18\x03 \x01(\v2\x11.titankv.KeyErrorR\bkeyError\"w\n" +
	"\rWriteConflict\x12\x19\n" +
	"\bstart_ts\x18\x01 \x01(\x04R\astartTs\x12\x1f\n" +
	"\vconflict_ts\x18\x02 \x01(\x04R\n" +
	"conflictTs\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12\x18\n" +
	"\aprimary\x18\x04 \x01(\fR\aprimary\"L\n" +
	"\bKeyError\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12.\n" +
	"\tlock_info\x18\x02 \x01(\v2\x11.titankv.LockInfoR\blockInfo\"b\n" +
	"\bLockInfo\x12!\n" +
	"\fprimary_lock\x18\x01 \x01(\fR\vprimaryLock\x12!\n" +
	"\flock_version\x18\x02 \x01(\x04R\vlockVersion\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x04R\x03ttl\"\x8d\x01\n" +
	"\rCommitRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.titankv.RegionContextR\acontext\x12\x19\n" +
	"\bstart_ts\x18\x02 \x01(\x04R\astartTs\x12\x1b\n" +
	"\tcommit_ts\x18\x03 \x01(\x04R\bcommitTs\x12\x12\n" +
	"\x04keys\x18\x04 \x03(\fR\x04keys\"&\n" +
	"\x0eCommitResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"k\n" +
	"\n" +
	"GetRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.titankv.RegionContextR\acontext\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x19\n" +
	"\bstart_ts\x18\x03 \x01(\x04R\astartTs\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"f\n" +
	"\n" +
	"PutRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.titankv.RegionContextR\acontext\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"E\n" +
	"\vPutResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x04R\bleaderId\"S\n" +
	"\rDeleteRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.titankv.RegionContextR\acontext\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"H\n" +
	"\x0eDeleteResponse\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x04R\bleaderId\"\x8c\x01\n" +
	"\x11RaftRequestHeader\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x127\n" +
	"\fregion_epoch\x18\x02 \x01(\v2\x14.titankv.RegionEpochR\vregionEpoch\x12!\n" +
	"\x04peer\x18\x03 \x01(\v2\r.titankv.PeerR\x04peer\"\xc5\x02\n" +
	"\vRaftCommand\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.titankv.RaftRequestHeaderR\x06header\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.titankv.RaftCommand.CmdTypeR\x04type\x12+\n" +
	"\x02op\x18\x03 \x01(\x0e2\x1b.titankv.RaftCommand.OpTypeR\x02op\x12\x10\n" +
	"\x03key\x18\x04 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x12:\n" +
	"\radmin_request\x18\x06 \x01(\v2\x15.titankv.AdminRequestR\fadminRequest\" \n" +
	"\aCmdType\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\t\n" +
	"\x05ADMIN\x10\x01\"\x1d\n" +
	"\x06OpType\x12\a\n" +
	"\x03PUT\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\"\xe9\x01\n" +
	"\fAdminRequest\x12=\n" +
	"\bcmd_type\x18\x01 \x01(\x0e2\".titankv.AdminRequest.AdminCmdTypeR\acmdType\x12+\n" +
	"\x05split\x18\x02 \x01(\v2\x15.titankv.SplitRequestR\x05split\x124\n" +
	"\vchange_peer\x18\x03 \x01(\v2\x13.titankv.ChangePeerR\n" +
	"changePeer\"7\n" +
	"\fAdminCmdType\x12\t\n" +
	"\x05SPLIT\x10\x00\x12\v\n" +
	"\aCOMPACT\x10\x01\x12\x0f\n" +
	"\vCONF_CHANGE\x10\x02\"{\n" +
	"\fSplitRequest\x12\x1b\n" +
	"\tsplit_key\x18\x01 \x01(\fR\bsplitKey\x12\"\n" +
	"\rnew_region_id\x18\x02 \x01(\x04R\vnewRegionId\x12*\n" +
	"\tnew_peers\x18\x04 \x03(\v2\r.titankv.PeerR\bnewPeers\"D\n" +
	"\x10BatchRaftCommand\x120\n" +
	"\bcommands\x18\x01 \x03(\v2\x14.titankv.RaftCommandR\bcommands\"\x9e\x01\n" +
	"\vRaftMessage\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1c\n" +
	"\n" +
	"to_peer_id\x18\x03 \x01(\x04R\btoPeerId\x12 \n" +
	"\ffrom_peer_id\x18\x04 \x01(\x04R\n" +
	"fromPeerId\x12\x1e\n" +
	"\vto_store_id\x18\x05 \x01(\x04R\ttoStoreId\"<\n" +
	"\x10BatchRaftMessage\x12(\n" +
	"\x04msgs\x18\x01 \x03(\v2\x14.titankv.RaftMessageR\x04msgs\"\x0e\n" +
	"\fRaftResponse\"o\n" +
	"\x0eRaftLocalState\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x12\n" +
	"\x04vote\x18\x02 \x01(\x04R\x04vote\x12\x16\n" +
	"\x06commit\x18\x03 \x01(\x04R\x06commit\x12\x1d\n" +
	"\n" +
	"last_index\x18\x04 \x01(\x04R\tlastIndex\"{\n" +
	"\x0eRaftApplyState\x12#\n" +
	"\rapplied_index\x18\x01 \x01(\x04R\fappliedIndex\x12D\n" +
	"\x0ftruncated_state\x18\x02 \x01(\v2\x1b.titankv.RaftTruncatedStateR\x0etruncatedState\">\n" +
	"\x12RaftTruncatedState\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\"8\n" +
	"\x13UpdateConfigRequest\x12!\n" +
	"\fgc_threshold\x18\x01 \x01(\x01R\vgcThreshold\"w\n" +
	"\x14RaftSnapshotMetadata\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x125\n" +
	"\n" +
	"conf_state\x18\x03 \x01(\v2\x16.titankv.RaftConfStateR\tconfState\"C\n" +
	"\rRaftConfState\x12\x16\n" +
	"\x06voters\x18\x01 \x03(\x04R\x06voters\x12\x1a\n" +
	"\blearners\x18\x02 \x03(\x04R\blearners\"\x16\n" +
	"\x14UpdateConfigResponse2\xac\x04\n" +
	"\aTitanKV\x120\n" +
	"\x03Get\x12\x13.titankv.GetRequest\x1a\x14.titankv.GetResponse\x120\n" +
	"\x03Put\x12\x13.titankv.PutRequest\x1a\x14.titankv.PutResponse\x129\n" +
	"\x06Delete\x12\x16.titankv.DeleteRequest\x1a\x17.titankv.DeleteResponse\x123\n" +
	"\x04Raft\x12\x14.titankv.RaftMessage\x1a\x15.titankv.RaftResponse\x12K\n" +
	"\fUpdateConfig\x12\x1c.titankv.UpdateConfigRequest\x1a\x1d.titankv.UpdateConfigResponse\x12A\n" +
	"\tBatchRaft\x12\x19.titankv.BatchRaftMessage\x1a\x15.titankv.RaftResponse(\x010\x01\x12A\n" +
	"\x0eStreamSnapshot\x12\x16.titankv.SnapshotChunk\x1a\x15.titankv.RaftResponse(\x01\x12?\n" +
	"\bPrewrite\x12\x18.titankv.PrewriteRequest\x1a\x19.titankv.PrewriteResponse\x129\n" +
	"\x06Commit\x12\x16.titankv.CommitRequest\x1a\x17.titankv.CommitResponseB\x17Z\x15titankv/api/titankvpbb\x06proto3"

var (
	file_titankv_proto_rawDescOnce sync.Once
	file_titankv_proto_rawDescData []byte
)

func file_titankv_proto_rawDescGZIP() []byte {
	file_titankv_proto_rawDescOnce.Do(func() {
		file_titankv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_titankv_proto_rawDesc), len(file_titankv_proto_rawDesc)))
	})
	return file_titankv_proto_rawDescData
}

var file_titankv_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_titankv_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_titankv_proto_goTypes = []any{
	(ChangePeer_ChangeType)(0),     // 0: titankv.ChangePeer.ChangeType
	(Mutation_Op)(0),               // 1: titankv.Mutation.Op
	(RaftCommand_CmdType)(0),       // 2: titankv.RaftCommand.CmdType
	(RaftCommand_OpType)(0),        // 3: titankv.RaftCommand.OpType
	(AdminRequest_AdminCmdType)(0), // 4: titankv.AdminRequest.AdminCmdType
	(*RegionEpoch)(nil),            // 5: titankv.RegionEpoch
	(*Peer)(nil),                   // 6: titankv.Peer
	(*ChangePeer)(nil),             // 7: titankv.ChangePeer
	(*Region)(nil),                 // 8: titankv.Region
	(*RegionContext)(nil),          // 9: titankv.RegionContext
	(*SnapshotChunk)(nil),          // 10: titankv.SnapshotChunk
	(*PrewriteRequest)(nil),        // 11: titankv.PrewriteRequest
	(*Mutation)(nil),               // 12: titankv.Mutation
	(*PrewriteResponse)(nil),       // 13: titankv.PrewriteResponse
	(*WriteConflict)(nil),          // 14: titankv.WriteConflict
	(*KeyError)(nil),               // 15: titankv.KeyError
	(*LockInfo)(nil),               // 16: titankv.LockInfo
	(*CommitRequest)(nil),          // 17: titankv.CommitRequest
	(*CommitResponse)(nil),         // 18: titankv.CommitResponse
	(*GetRequest)(nil),             // 19: titankv.GetRequest
	(*GetResponse)(nil),            // 20: titankv.GetResponse
	(*PutRequest)(nil),             // 21: titankv.PutRequest
	(*PutResponse)(nil),            // 22: titankv.PutResponse
	(*DeleteRequest)(nil),          // 23: titankv.DeleteRequest
	(*DeleteResponse)(nil),         // 24: titankv.DeleteResponse
	(*RaftRequestHeader)(nil),      // 25: titankv.RaftRequestHeader
	(*RaftCommand)(nil),            // 26: titankv.RaftCommand
	(*AdminRequest)(nil),           // 27: titankv.AdminRequest
	(*SplitRequest)(nil),           // 28: titankv.SplitRequest
	(*BatchRaftCommand)(nil),       // 29: titankv.BatchRaftCommand
	(*RaftMessage)(nil),            // 30: titankv.RaftMessage
	(*BatchRaftMessage)(nil),       // 31: titankv.BatchRaftMessage
	(*RaftResponse)(nil),           // 32: titankv.RaftResponse
	(*RaftLocalState)(nil),         // 33: titankv.RaftLocalState
	(*RaftApplyState)(nil),         // 34: titankv.RaftApplyState
	(*RaftTruncatedState)(nil),     // 35: titankv.RaftTruncatedState
	(*UpdateConfigRequest)(nil),    // 36: titankv.UpdateConfigRequest
	(*RaftSnapshotMetadata)(nil),   // 37: titankv.RaftSnapshotMetadata
	(*RaftConfState)(nil),          // 38: titankv.RaftConfState
	(*UpdateConfigResponse)(nil),   // 39: titankv.UpdateConfigResponse
}
var file_titankv_proto_depIdxs = []int32{
	0,  // 0: titankv.ChangePeer.change_type:type_name -> titankv.ChangePeer.ChangeType
	6,  // 1: titankv.ChangePeer.peer:type_name -> titankv.Peer
	5,  // 2: titankv.Region.region_epoch:type_name -> titankv.RegionEpoch
	6,  // 3: titankv.Region.peers:type_name -> titankv.Peer
	5,  // 4: titankv.RegionContext.region_epoch:type_name -> titankv.RegionEpoch
	6,  // 5: titankv.RegionContext.peer:type_name -> titankv.Peer
	9,  // 6: titankv.PrewriteRequest.context:type_name -> titankv.RegionContext
	12, // 7: titankv.PrewriteRequest.mutations:type_name -> titankv.Mutation
	1,  // 8: titankv.Mutation.op:type_name -> titankv.Mutation.Op
	14, // 9: titankv.PrewriteResponse.conflict:type_name -> titankv.WriteConflict
	15, // 10: titankv.PrewriteResponse.key_error:type_name -> titankv.KeyError
	16, // 11: titankv.KeyError.lock_info:type_name -> titankv.LockInfo
	9,  // 12: titankv.CommitRequest.context:type_name -> titankv.RegionContext
	9,  // 13: titankv.GetRequest.context:type_name -> titankv.RegionContext
	9,  // 14: titankv.PutRequest.context:type_name -> titankv.RegionContext
	9,  // 15: titankv.DeleteRequest.context:type_name -> titankv.RegionContext
	5,  // 16: titankv.RaftRequestHeader.region_epoch:type_name -> titankv.RegionEpoch
	6,  // 17: titankv.RaftRequestHeader.peer:type_name -> titankv.Peer
	25, // 18: titankv.RaftCommand.header:type_name -> titankv.RaftRequestHeader
	2,  // 19: titankv.RaftCommand.type:type_name -> titankv.RaftCommand.CmdType
	3,  // 20: titankv.RaftCommand.op:type_name -> titankv.RaftCommand.OpType
	27, // 21: titankv.RaftCommand.admin_request:type_name -> titankv.AdminRequest
	4,  // 22: titankv.AdminRequest.cmd_type:type_name -> titankv.AdminRequest.AdminCmdType
	28, // 23: titankv.AdminRequest.split:type_name -> titankv.SplitRequest
	7,  // 24: titankv.AdminRequest.change_peer:type_name -> titankv.ChangePeer
	6,  // 25: titankv.SplitRequest.new_peers:type_name -> titankv.Peer
	26, // 26: titankv.BatchRaftCommand.commands:type_name -> titankv.RaftCommand
	30, // 27: titankv.BatchRaftMessage.msgs:type_name -> titankv.RaftMessage
	35, // 28: titankv.RaftApplyState.truncated_state:type_name -> titankv.RaftTruncatedState
	38, // 29: titankv.RaftSnapshotMetadata.conf_state:type_name -> titankv.RaftConfState
	19, // 30: titankv.TitanKV.Get:input_type -> titankv.GetRequest
	21, // 31: titankv.TitanKV.Put:input_type -> titankv.PutRequest
	23, // 32: titankv.TitanKV.Delete:input_type -> titankv.DeleteRequest
	30, // 33: titankv.TitanKV.Raft:input_type -> titankv.RaftMessage
	36, // 34: titankv.TitanKV.UpdateConfig:input_type -> titankv.UpdateConfigRequest
	31, // 35: titankv.TitanKV.BatchRaft:input_type -> titankv.BatchRaftMessage
	10, // 36: titankv.TitanKV.StreamSnapshot:input_type -> titankv.SnapshotChunk
	11, // 37: titankv.TitanKV.Prewrite:input_type -> titankv.PrewriteRequest
	17, // 38: titankv.TitanKV.Commit:input_type -> titankv.CommitRequest
	20, // 39: titankv.TitanKV.Get:output_type -> titankv.GetResponse
	22, // 40: titankv.TitanKV.Put:output_type -> titankv.PutResponse
	24, // 41: titankv.TitanKV.Delete:output_type -> titankv.DeleteResponse
	32, // 42: titankv.TitanKV.Raft:output_type -> titankv.RaftResponse
	39, // 43: titankv.TitanKV.UpdateConfig:output_type -> titankv.UpdateConfigResponse
	32, // 44: titankv.TitanKV.BatchRaft:output_type -> titankv.RaftResponse
	32, // 45: titankv.TitanKV.StreamSnapshot:output_type -> titankv.RaftResponse
	13, // 46: titankv.TitanKV.Prewrite:output_type -> titankv.PrewriteResponse
	18, // 47: titankv.TitanKV.Commit:output_type -> titankv.CommitResponse
	39, // [39:48] is the sub-list for method output_type
	30, // [30:39] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_titankv_proto_init() }
func file_titankv_proto_init() {
	if File_titankv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_titankv_proto_rawDesc), len(file_titankv_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_titankv_proto_goTypes,
		DependencyIndexes: file_titankv_proto_depIdxs,
		EnumInfos:         file_titankv_proto_enumTypes,
		MessageInfos:      file_titankv_proto_msgTypes,
	}.Build()
	File_titankv_proto = out.File
	file_titankv_proto_goTypes = nil
	file_titankv_proto_depIdxs = nil
}
