// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: titankv.proto

package titankvpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TitanKV_Get_FullMethodName            = "/titankv.TitanKV/Get"
	TitanKV_Put_FullMethodName            = "/titankv.TitanKV/Put"
	TitanKV_Delete_FullMethodName         = "/titankv.TitanKV/Delete"
	TitanKV_Raft_FullMethodName           = "/titankv.TitanKV/Raft"
	TitanKV_UpdateConfig_FullMethodName   = "/titankv.TitanKV/UpdateConfig"
	TitanKV_BatchRaft_FullMethodName      = "/titankv.TitanKV/BatchRaft"
	TitanKV_StreamSnapshot_FullMethodName = "/titankv.TitanKV/StreamSnapshot"
)

// TitanKVClient is the client API for TitanKV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义 KV 服务
type TitanKVClient interface {
	// Client API
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// 【新增】Raft Node API
	// 用于节点间传输 Raft 消息 (Vote, AppendEntries, etc.)
	Raft(ctx context.Context, in *RaftMessage, opts ...grpc.CallOption) (*RaftResponse, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
	// 双向流：Client 发 Batch，Server 回 Response (可以不回)
	BatchRaft(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchRaftMessage, RaftResponse], error)
	StreamSnapshot(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SnapshotChunk, RaftResponse], error)
}

type titanKVClient struct {
	cc grpc.ClientConnInterface
}

func NewTitanKVClient(cc grpc.ClientConnInterface) TitanKVClient {
	return &titanKVClient{cc}
}

func (c *titanKVClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, TitanKV_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *titanKVClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, TitanKV_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *titanKVClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, TitanKV_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *titanKVClient) Raft(ctx context.Context, in *RaftMessage, opts ...grpc.CallOption) (*RaftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RaftResponse)
	err := c.cc.Invoke(ctx, TitanKV_Raft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *titanKVClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigResponse)
	err := c.cc.Invoke(ctx, TitanKV_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *titanKVClient) BatchRaft(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchRaftMessage, RaftResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TitanKV_ServiceDesc.Streams[0], TitanKV_BatchRaft_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchRaftMessage, RaftResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TitanKV_BatchRaftClient = grpc.BidiStreamingClient[BatchRaftMessage, RaftResponse]

func (c *titanKVClient) StreamSnapshot(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SnapshotChunk, RaftResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TitanKV_ServiceDesc.Streams[1], TitanKV_StreamSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapshotChunk, RaftResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TitanKV_StreamSnapshotClient = grpc.ClientStreamingClient[SnapshotChunk, RaftResponse]

// TitanKVServer is the server API for TitanKV service.
// All implementations must embed UnimplementedTitanKVServer
// for forward compatibility.
//
// 定义 KV 服务
type TitanKVServer interface {
	// Client API
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// 【新增】Raft Node API
	// 用于节点间传输 Raft 消息 (Vote, AppendEntries, etc.)
	Raft(context.Context, *RaftMessage) (*RaftResponse, error)
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
	// 双向流：Client 发 Batch，Server 回 Response (可以不回)
	BatchRaft(grpc.BidiStreamingServer[BatchRaftMessage, RaftResponse]) error
	StreamSnapshot(grpc.ClientStreamingServer[SnapshotChunk, RaftResponse]) error
	mustEmbedUnimplementedTitanKVServer()
}

// UnimplementedTitanKVServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTitanKVServer struct{}

func (UnimplementedTitanKVServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTitanKVServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedTitanKVServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTitanKVServer) Raft(context.Context, *RaftMessage) (*RaftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Raft not implemented")
}
func (UnimplementedTitanKVServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedTitanKVServer) BatchRaft(grpc.BidiStreamingServer[BatchRaftMessage, RaftResponse]) error {
	return status.Error(codes.Unimplemented, "method BatchRaft not implemented")
}
func (UnimplementedTitanKVServer) StreamSnapshot(grpc.ClientStreamingServer[SnapshotChunk, RaftResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamSnapshot not implemented")
}
func (UnimplementedTitanKVServer) mustEmbedUnimplementedTitanKVServer() {}
func (UnimplementedTitanKVServer) testEmbeddedByValue()                 {}

// UnsafeTitanKVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TitanKVServer will
// result in compilation errors.
type UnsafeTitanKVServer interface {
	mustEmbedUnimplementedTitanKVServer()
}

func RegisterTitanKVServer(s grpc.ServiceRegistrar, srv TitanKVServer) {
	// If the following call panics, it indicates UnimplementedTitanKVServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TitanKV_ServiceDesc, srv)
}

func _TitanKV_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TitanKVServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TitanKV_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TitanKVServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TitanKV_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TitanKVServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TitanKV_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TitanKVServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TitanKV_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TitanKVServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TitanKV_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TitanKVServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TitanKV_Raft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TitanKVServer).Raft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TitanKV_Raft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TitanKVServer).Raft(ctx, req.(*RaftMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TitanKV_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TitanKVServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TitanKV_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TitanKVServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TitanKV_BatchRaft_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TitanKVServer).BatchRaft(&grpc.GenericServerStream[BatchRaftMessage, RaftResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TitanKV_BatchRaftServer = grpc.BidiStreamingServer[BatchRaftMessage, RaftResponse]

func _TitanKV_StreamSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TitanKVServer).StreamSnapshot(&grpc.GenericServerStream[SnapshotChunk, RaftResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TitanKV_StreamSnapshotServer = grpc.ClientStreamingServer[SnapshotChunk, RaftResponse]

// TitanKV_ServiceDesc is the grpc.ServiceDesc for TitanKV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TitanKV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "titankv.TitanKV",
	HandlerType: (*TitanKVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _TitanKV_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _TitanKV_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TitanKV_Delete_Handler,
		},
		{
			MethodName: "Raft",
			Handler:    _TitanKV_Raft_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _TitanKV_UpdateConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BatchRaft",
			Handler:       _TitanKV_BatchRaft_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamSnapshot",
			Handler:       _TitanKV_StreamSnapshot_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "titankv.proto",
}
